version: '3'
services:
  inpaint-app:
    build: ./inpaint
    volumes:
      - ./inpaint:/home/inpaint
      - ./inputs:/inputs
      - ./results:/results
    tty: true
  inpaint-app-v2:
    build: ./inpaint_v2
    volumes:
      - ./inpaint_v2:/home/inpaint_v2
      - ./inputs:/inputs
      - ./results:/results
    tty: true  